# Generated by Django 5.1.3 on 2024-12-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_order_cost_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hotel',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
