# Generated by Django 5.1.3 on 2024-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_order_hotel_alter_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Packing', 'Packing'), ('In-transit', 'Intransit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Packing', max_length=50),
        ),
    ]
