# Generated by Django 5.1.3 on 2024-12-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_image',
            field=models.ImageField(default='hotel_default.png', upload_to='hotels/'),
        ),
    ]
